[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# Example, use the version numbers you need

# for backend and async
tide = "0.17.0-beta.1" 
serde = { version = "1.0", features = ["derive"] }
async-std = { version = "1.8.0", features = ["attributes"] }
femme = "2.2.1"
